### ISSUE TITLE
Cart functionality

### ISSUE THREAD

**Issue by arnav-deep** [arnav-deep/FoodShala#5]
Add a cart functionality to order instead of a direct order button in the [orders.php](https://github.com/arnav-deep/FoodShala/blob/master/orders.php) page.

**Comment by sptutusukanta** [comment]
Hi @arnav-deep I'm on it.. :) 
Happy Hacktoberfest

**Comment by arnav-deep** [comment]
Hi @sptutusukanta 
Assigning it to you. Thank you. If you have any doubts in the source code, feel free to ask here. Will be active here.

**Comment by sptutusukanta** [comment]
Hi @arnav-deep, I check the app on my local, but before proceeding further, I want to know if this is a college project or just for fun & learn kind of project. Or are you into making into something real?

Because at the current level I see a lot of issues, if it's for learning, then it's okay. If not, then this won't work in real.
Based on this we may go forward, so, please let me know.

**Comment by arnav-deep** [comment]
Hey @sptutusukanta 

So yeah, this was made just for learning, nothing real. You can add functionalities as you want. I do have seen some issues but they didn't affect the normal flow as of yet. Adding the cart function will change a lot of things in [orders.php](https://github.com/arnav-deep/FoodShala/blob/master/orsers.php), including the way the food is ordered now.

If you do notice any issues or functionality worth changing or adding, do get in touch with me or comment here. I will either work on it on my own or add them as issues. For now, you can just add the basic add to cart and checkout functionality considering it as a small project, not for deployment.

**Comment by sptutusukanta** [comment]
Okay, cool, just for fun try this as the login email, with any password (doesn't matter)
email: `' or '1'='1`
pass: `anything`

Just make sure to use developer tools and change input type to `text` from `email` and see what happens.

**Comment by arnav-deep** [comment]
Tried.

Can you explain why it was accepted?

**Comment by sptutusukanta** [comment]
The first step would be to add some kind of cart functionality session.

The next step, as the orders and items are taken directly in the `orders` table, it is required to be split:
1. orders: having the order related info (who ordered, when, to which restaurant etc. but not the ordered items)
2. order_items: this will be a table referencing with a foreign key to point orders.

**Comment by sptutusukanta** [comment]
> Tried.
> 
> Can you explain why it was accepted?

Its a pure & simple SQL injection attack. You may learn more here: https://www.guru99.com/learn-sql-injection-with-practical-example.html

**Comment by arnav-deep** [comment]
Thanks for sharing that.
Although this attack would fail if the input is only taken as email, right?

**Comment by sptutusukanta** [comment]
Nopes, if you validate in HTML side, anyone can just open devtools and change that.. But if you validate in PHP/server-side, yes then it can be protected, but again, the password is not protected, so another kind of attack might be possible.

**Comment by arnav-deep** [comment]
> The first step would be to add some kind of cart functionality session.
> 
> The next step, as the orders and items are taken directly in the `orders` table, it is required to be split:
> 
> 1. orders: having the order related info (who ordered, when, to which restaurant etc. but not the ordered items)
> 2. order_items: this will be a table referencing with a foreign key to point orders.

Yeah, the database will require altering. You can make the alterations as you want.

**Comment by sptutusukanta** [comment]
There would a lot of attacks possible, as done in your app, not only in login but in other places too.. So, try to learn & implement mysqli / PDO prepared statements.

**Comment by sptutusukanta** [comment]
> > The first step would be to add some kind of cart functionality session.
> > The next step, as the orders and items are taken directly in the `orders` table, it is required to be split:
> > 
> > 1. orders: having the order related info (who ordered, when, to which restaurant etc. but not the ordered items)
> > 2. order_items: this will be a table referencing with a foreign key to point orders.
> 
> Yeah, the database will require altering. You can make the alterations as you want.

Yeah will do.

**Comment by arnav-deep** [comment]
> Nopes, if you validate in HTML side, anyone can just open devtools and change that.. But if you validate in PHP/server-side, yes then it can be protected, but again, the password is not protected, so another kind of attack might be possible.

Ok. Will look it and add it. I did not put protection as I was just building it for learning.

**Comment by sptutusukanta** [comment]
> > Nopes, if you validate in HTML side, anyone can just open devtools and change that.. But if you validate in PHP/server-side, yes then it can be protected, but again, the password is not protected, so another kind of attack might be possible.
> 
> Ok. Will look it and add it. I did not put protection as I was just building it for learning.

Yes, I understand but also learn to protect.

**Comment by arnav-deep** [comment]
> > > Nopes, if you validate in HTML side, anyone can just open devtools and change that.. But if you validate in PHP/server-side, yes then it can be protected, but again, the password is not protected, so another kind of attack might be possible.
> > 
> > 
> > Ok. Will look it and add it. I did not put protection as I was just building it for learning.
> 
> Yes, I understand but also learn to protect.

Yeah. I will update the security. Leave that part to me.

**Comment by sptutusukanta** [comment]
By the way what you actually do?
Do you have friends working/learning on the same trade?

I mean, why not make something in real? See, I'm a freelance developer & designer and work for me & for my family. I am in this trade for around 7 years. If you are interested (apart from this project) you may send your contact info to sptutusukanta@gmail.com

------------

Anyway, my next update would be to build the cart using Session, possibly tonight or tomorrow. See you then.

**Comment by sptutusukanta** [comment]
Hi.. please check the PR, if you plan to merge it later, please add `hacktoberfest-accepted` label to the requested PR.

**Comment by arnav-deep** [comment]
Hey @sptutusukanta !

Will check and merge within 12 hours. Will also add the label. Thank you for your work.
